name: Publish Qinile Core to Nuget
on:
  push:
    branches:
      - main # Default release branch

env:
  DOTNET_VERSION: '3.1.x'
  PACKAGE_MAJOR_VERSION: 0
  PACKAGE_MINOR_VERSION: 0
  PACKAGE_VERSION: $PACKAGE_MAJOR_VERSION.$PACKAGE_MINOR_VERSION.$GITHUB_RUN_NUMBER
  REPOSITORY_URL: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Pack & Publish
    steps:

      # Configuration

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Dotnet ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      # Build

      - name: Dotnet Build Qinile.Core
        run: dotnet build source/Qinile.Core/Qinile.Core.csproj --configuration Release

      - name: Dotnet Pack Qinile.Core
        run: dotnet pack source/Qinile.Core/Qinile.Core.csproj --configuration Release --include-symbols --include-source -o out -p:PackageVersion=${{env.PACKAGE_VERSION}}

      - name: Dotnet Build Qinile.Core.Behaviours
        run: dotnet build source/Qinile.Core.Behaviours/Qinile.Core.Behaviours.csproj --configuration Release

      - name: Dotnet Pack Qinile.Core.Behaviours
        run: dotnet pack source/Qinile.Core.Behaviours/Qinile.Core.Behaviours.csproj --configuration Release --include-symbols --include-source -o out -p:PackageVersion=${{env.PACKAGE_VERSION}}

      # Push
      - name: Dotnet Push
        run: dotnet nuget push out/*.nupkg --source ${{env.REPOSITORY_URL}} --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
    